# Generated by Django 3.1.6 on 2021-04-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='comments',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
