# Generated by Django 3.1.6 on 2021-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='thursday1',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='hours',
            name='friday_close',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='friday_open',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='monday_close',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='monday_open',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='saturday_close',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='saturday_open',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='sunday_close',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='sunday_open',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='thursday_close',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='thursday_open',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='tuesday_close',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='tuesday_open',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='wednesday_open',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
