# Generated by Django 3.1.7 on 2021-04-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
