# Generated by Django 3.1.6 on 2021-04-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_truck_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='comments',
        ),
    ]
