# Generated by Django 3.1.6 on 2021-04-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210405_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
