# Generated by Django 3.1.6 on 2021-04-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='food_description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='food_price',
        ),
    ]
