# Generated by Django 3.1.6 on 2021-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210407_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='num_reviews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
